name: mismedidasb
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.2+14

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.16.0
  rxdart: 0.23.1
  kiwi: ^0.2.0
  http: ^0.12.0+4
  dio: ^2.1.0
  shared_preferences: ^0.5.6
  cached_network_image: ^2.0.0
  fluttertoast: ^3.1.3
  path_provider: ^1.5.1
  sqflite: ^1.2.0
  image_picker: ^0.6.3+1
  material_design_icons_flutter: ^3.4.4895
  cupertino_icons: ^0.1.2
#  signalr_client: ^0.1.6
  charts_flutter: ^0.9.0
#  mp_chart: ^0.1.8
  flutter_rounded_progress_bar: ^0.1.2
  device_info: ^0.4.2+1
  photo_view: ^0.9.2
  firebase_messaging: ^6.0.13
#  flutter_apns: ^1.1.0
  webview_flutter: ^0.3.19+9
  flutter_html: ^0.11.1
  table_calendar: ^2.2.3
#  local_auth: ^0.6.1+3
  permission_handler: ^5.0.0+hotfix.3
#  flutter_mailer: ^0.4.2

#  cloud_firestore: ^0.13.0+1
#  firebase_auth: ^0.15.3+1
#  google_sign_in: ^4.1.1
#  firebase_crashlytics: ^0.1.2+4
#  firebase_analytics: ^5.0.9
#  google_fonts: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/res/assets/
    - lib/res/assets/img/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Fira
      fonts:
        - asset: lib/res/assets/fonts/fira_code_bold_700.ttf
        - asset: lib/res/assets/fonts/fira_code_light_300.ttf
        - asset: lib/res/assets/fonts/fira_code_medium_500.ttf
        - asset: lib/res/assets/fonts/fira_code_regular_400.ttf
        - asset: lib/res/assets/fonts/fira_code_retina_450.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
